Data:
  baresoil_samples:
  - ../code/baresoil/switzerland_fields/sampled_soil_spectra_Switzerland_35.csv
  data_path:
  - ProSAIL_forward/results/switzerland/prosail_danner-etal_switzerland_soil_S2A_lut_35.pkl
  - ProSAIL_forward/results/switzerland/prosail_danner-etal_switzerland_soil_snap_S2B_lut_35.pkl
  normalize: true
  target_col: lai
  test_data_path:
  - ProSAIL_forward/results/switzerland/test/prosail_danner-etal_switzerland_soil_snap_S2A_lut_35.pkl
  - ProSAIL_forward/results/switzerland/test/prosail_danner-etal_switzerland_soil_snap_S2B_lut_35.pkl
  train_cols:
  - B02
  - B03
  - B04
  - B05
  - B06
  - B07
  - B08
  - B8A
  - B11
  - B12
  val_data_path:
  - ../data/insitu_S2/switzerland_fields/s2_val_licor_Altkloster_clean.pkl
  - ../data/insitu_S2/switzerland_fields/s2_val_licor_Bramenwies_clean.pkl
  - ../data/insitu_S2/switzerland_fields/s2_val_licor_Broatefaeld_clean.pkl
  - ../data/insitu_S2/switzerland_fields/s2_val_licor_Fluegenrain_clean.pkl
  - ../data/insitu_S2/switzerland_fields/s2_val_licor_Grund_clean.pkl
  - ../data/insitu_S2/switzerland_fields/s2_val_licor_Hohrueti_clean.pkl
  - ../data/insitu_S2/switzerland_fields/s2_val_licor_Hohrueti2_clean.pkl
  - ../data/insitu_S2/switzerland_fields/s2_val_licor_Neuhof3_clean.pkl
  - ../data/insitu_S2/switzerland_fields/s2_val_licor_Ruetteli_clean.pkl
Model:
  batch_size: 64
  criterion: MSE
  epochs: 1
  gpu: false
  hidden_layer: 1
  hidden_size: 64
  input_size: 10
  name: NN
  noise: true
  optim:
    lr: 0.009883206697453932
    name: Adam
  output_size: 1
  plot: true
  save: true
  save_path: ../models/NN_CH_soil_35.pkl
  scheduler:
    name: ReduceLROnPlateau
  score_path: null
Seed:
- 0
- 1
- 2
- 3
- 4
Tuning:
  n_trials: 10
